var devicesData = {
  "2828395011653632098123456":{
    "id":"2843974937874432",
    "name":"Rack 1",
    "dn":"2828395011653632098123456",
    "type":"rack",
    "uTotalNumber":"46",
    "front":"images/Navigation_icon/icon_rack.png",
    "rear":"images/Navigation_icon/icon_rack.png",
    "children":[
      {
        "endU":"18",
        "name":"Server 24",
        "model":"RackServer 24",
        "id":"30502629741639111",
        "type":"RackServer",
        "startU":"17"
      },
      {
        "endU":"32",
        "name":"Server 12",
        "model":"BladeServer 1",
        "id":"40188821841851304",
        "type":"BladeServer",
        "startU":"31"
      },
      {
        "endU":"2",
        "name":"Server 30",
        "model":"StorageServer 1",
        "id":"43256524543638243",
        "type":"StorageServer",
        "startU":"1"
      },
      {
        "endU":"16",
        "name":"rPDU",
        "model":"rPDU 1",
        "location":"left",
        "id":"43546974813015814",
        "type":"rPDU",
        "startU":"2",
        "powerConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          }
        ],
        "networkConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          },
          {
            port:'3',
            status:'1'
          },
          {
            port:'4',
            status:'2'
          },
          {
            port:'5',
            status:'1'
          },
          {
            port:'6',
            status:'1'
          },
          {
            port:'7',
            status:'2'
          },
          {
            port:'8',
            status:'2'
          },
          {
            port:'9',
            status:'1'
          },
          {
            port:'10',
            status:'1'
          },
          {
            port:'11',
            status:'2'
          },
          {
            port:'12',
            status:'1'
          },
          {
            port:'13',
            status:'1'
          }
        ]
      },
      {
        "endU":"18",
        "name":"Server 24",
        "model":"RackServer 24",
        "location":"right",
        "id":"56271197342150865",
        "type":"RackServer",
        "startU":"17",
        "powerConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          }
        ],
        "networkConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          },
          {
            port:'3',
            status:'1'
          },
          {
            port:'4',
            status:'2'
          },
          {
            port:'5',
            status:'1'
          },
          {
            port:'6',
            status:'1'
          },
          {
            port:'7',
            status:'2'
          },
          {
            port:'8',
            status:'2'
          },
          {
            port:'9',
            status:'1'
          },
          {
            port:'10',
            status:'1'
          },
          {
            port:'11',
            status:'2'
          },
          {
            port:'12',
            status:'1'
          },
          {
            port:'13',
            status:'1'
          }
        ]
      },
      /*{
        "endU":"18",
        "name":"Server 24",
        "model":"RackServer 24",
        "location":"right",
        "id":"56271197342150865",
        "type":"RackServer",
        "startU":"17",
        "powerConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          }
        ],
        "networkConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          },
          {
            port:'3',
            status:'1'
          },
          {
            port:'4',
            status:'2'
          },
          {
            port:'5',
            status:'1'
          },
          {
            port:'6',
            status:'1'
          },
          {
            port:'7',
            status:'2'
          },
          {
            port:'8',
            status:'2'
          },
          {
            port:'9',
            status:'1'
          },
          {
            port:'10',
            status:'1'
          },
          {
            port:'11',
            status:'2'
          },
          {
            port:'12',
            status:'1'
          },
          {
            port:'13',
            status:'1'
          }
        ]
      },*/
      {
        "endU":"32",
        "name":"Server 12",
        "model":"BladeServer 1",
        "id":"60610560681981112",
        "type":"BladeServer",
        "startU":"31"
      },
      {
        "endU":"2",
        "name":"Server 30",
        "model":"StorageServer 1",
        "id":"69363434410790117",
        "type":"StorageServer",
        "startU":"1"
      },
      {
        "endU":"16",
        "name":"rPDU",
        "model":"rPDU 1",
        "location":"left",
        "id":"80991706029474097",
        "type":"rPDU",
        "startU":"2",
        "powerConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          }
        ],
        "networkConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          },
          {
            port:'3',
            status:'1'
          },
          {
            port:'4',
            status:'2'
          },
          {
            port:'5',
            status:'1'
          },
          {
            port:'6',
            status:'1'
          },
          {
            port:'7',
            status:'2'
          },
          {
            port:'8',
            status:'2'
          },
          {
            port:'9',
            status:'1'
          },
          {
            port:'10',
            status:'1'
          },
          {
            port:'11',
            status:'2'
          },
          {
            port:'12',
            status:'1'
          },
          {
            port:'13',
            status:'1'
          }
        ]
      },
      {
        "endU":"16",
        "name":"rPDU 2",
        "model":"rPDU 1",
        "location":"right",
        "id":"88615581520937709",
        "type":"rPDU",
        "startU":"2",
        "powerConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          }
        ],
        "networkConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          },
          {
            port:'3',
            status:'1'
          },
          {
            port:'4',
            status:'2'
          },
          {
            port:'5',
            status:'1'
          },
          {
            port:'6',
            status:'1'
          },
          {
            port:'7',
            status:'2'
          },
          {
            port:'8',
            status:'2'
          },
          {
            port:'9',
            status:'1'
          },
          {
            port:'10',
            status:'1'
          },
          {
            port:'11',
            status:'2'
          },
          {
            port:'12',
            status:'1'
          },
          {
            port:'13',
            status:'1'
          }
        ]
      }
    ],
    "utotalNumber":"46"
  },
  "2843974937871232099123455":{
    "id":"2843976516505601",
    "name":"rack2",
    "dn":"2843974937871232099123455",
    "type":"rack",
    "uTotalNumber":"46",
    "front":"images/Navigation_icon/icon_rack.png",
    "rear":"images/Navigation_icon/icon_rack.png",
    "children":[
      {
        "endU":"18",
        "name":"Server 24",
        "model":"RackServer 24",
        "id":"30502629741639111",
        "type":"RackServer",
        "startU":"17"
      },
      {
        "endU":"32",
        "name":"Server 12",
        "model":"BladeServer 1",
        "id":"40188821841851304",
        "type":"BladeServer",
        "startU":"31"
      },
      {
        "endU":"2",
        "name":"Server 30",
        "model":"StorageServer 1",
        "id":"43256524543638243",
        "type":"StorageServer",
        "startU":"1"
      },
      {
        "endU":"16",
        "name":"rPDU",
        "model":"rPDU 1",
        "location":"left",
        "id":"43546974813015814",
        "type":"rPDU",
        "startU":"2",
        "powerConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          }
        ],
        "networkConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          },
          {
            port:'3',
            status:'1'
          },
          {
            port:'4',
            status:'2'
          },
          {
            port:'5',
            status:'1'
          },
          {
            port:'6',
            status:'1'
          },
          {
            port:'7',
            status:'2'
          },
          {
            port:'8',
            status:'2'
          },
          {
            port:'9',
            status:'1'
          },
          {
            port:'10',
            status:'1'
          },
          {
            port:'11',
            status:'2'
          },
          {
            port:'12',
            status:'1'
          },
          {
            port:'13',
            status:'1'
          }
        ]
      },
      /*{
        "endU":"18",
        "name":"Server 24",
        "model":"RackServer 24",
        "location":"right",
        "id":"56271197342150865",
        "type":"RackServer",
        "startU":"17",
        "powerConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          }
        ],
        "networkConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          },
          {
            port:'3',
            status:'1'
          },
          {
            port:'4',
            status:'2'
          },
          {
            port:'5',
            status:'1'
          },
          {
            port:'6',
            status:'1'
          },
          {
            port:'7',
            status:'2'
          },
          {
            port:'8',
            status:'2'
          },
          {
            port:'9',
            status:'1'
          },
          {
            port:'10',
            status:'1'
          },
          {
            port:'11',
            status:'2'
          },
          {
            port:'12',
            status:'1'
          },
          {
            port:'13',
            status:'1'
          }
        ]
      },
      {
        "endU":"18",
        "name":"Server 24",
        "model":"RackServer 24",
        "location":"right",
        "id":"56271197342150865",
        "type":"RackServer",
        "startU":"17",
        "powerConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          }
        ],
        "networkConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          },
          {
            port:'3',
            status:'1'
          },
          {
            port:'4',
            status:'2'
          },
          {
            port:'5',
            status:'1'
          },
          {
            port:'6',
            status:'1'
          },
          {
            port:'7',
            status:'2'
          },
          {
            port:'8',
            status:'2'
          },
          {
            port:'9',
            status:'1'
          },
          {
            port:'10',
            status:'1'
          },
          {
            port:'11',
            status:'2'
          },
          {
            port:'12',
            status:'1'
          },
          {
            port:'13',
            status:'1'
          }
        ]
      },*/
      {
        "endU":"32",
        "name":"Server 12",
        "model":"BladeServer 1",
        "id":"60610560681981112",
        "type":"BladeServer",
        "startU":"31"
      },
      {
        "endU":"2",
        "name":"Server 30",
        "model":"StorageServer 1",
        "id":"69363434410790117",
        "type":"StorageServer",
        "startU":"1"
      },
      {
        "endU":"16",
        "name":"rPDU",
        "model":"rPDU 1",
        "location":"left",
        "id":"80991706029474097",
        "type":"rPDU",
        "startU":"2",
        "powerConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          }
        ],
        "networkConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          },
          {
            port:'3',
            status:'1'
          },
          {
            port:'4',
            status:'2'
          },
          {
            port:'5',
            status:'1'
          },
          {
            port:'6',
            status:'1'
          },
          {
            port:'7',
            status:'2'
          },
          {
            port:'8',
            status:'2'
          },
          {
            port:'9',
            status:'1'
          },
          {
            port:'10',
            status:'1'
          },
          {
            port:'11',
            status:'2'
          },
          {
            port:'12',
            status:'1'
          },
          {
            port:'13',
            status:'1'
          }
        ]
      },
      {
        "endU":"16",
        "name":"rPDU 2",
        "model":"rPDU 1",
        "location":"right",
        "id":"88615581520937709",
        "type":"rPDU",
        "startU":"2",
        "powerConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          }
        ],
        "networkConnects":[
          {
            port:'1',
            status:'1'
          },
          {
            port:'2',
            status:'2'
          },
          {
            port:'3',
            status:'1'
          },
          {
            port:'4',
            status:'2'
          },
          {
            port:'5',
            status:'1'
          },
          {
            port:'6',
            status:'1'
          },
          {
            port:'7',
            status:'2'
          },
          {
            port:'8',
            status:'2'
          },
          {
            port:'9',
            status:'1'
          },
          {
            port:'10',
            status:'1'
          },
          {
            port:'11',
            status:'2'
          },
          {
            port:'12',
            status:'1'
          },
          {
            port:'13',
            status:'1'
          }
        ]
      }
    ],
    "utotalNumber":"46"
  }
};
