var $Defaults = {

    COLORS: ['#6495ED', '#FFFF00', '#00FFFF', '#FF0000', '#7FFF00', '#E0A580', '#5FC0CB', '#FA00F0', '#A1BC50',
    '#FFD700', '#4169E1', '#E5A5F5', '#1E90FF', '#696969', '#FF6347', '#00BFEF', '#FFD700', '#80E090',
    '#5F9EA0', '#A000FF', '#7FAF00', '#228BA2', '#FF00FF', '#7FFFD4', '#800000', '#0000CD', '#20B2AA',
    '#D2691E', '#6495BD', '#DC143C', '#F0A8AF', '#008B8B', '#800080', '#B8860B', '#4B0082', '#00FF00',
    '#FFA500', '#FF4500', '#FFFF00', '#9ACD32', '#00008B', '#FF1493', '#ADFF2F', '#4682B4', '#00C0B1'],

    CALL_LATER_DELAY: 17,
    SCROLL_BAR_WIDTH: 17,
    SELECT_COLOR: '#C2CFF1',
    FOCUS_ON_CLICK: true,

    VIEW_POSITION: 'absolute',
    VIEW_FONT_SIZE: '12px',
    VIEW_FONT_FAMILY: 'arial, tahoma, helvetica, sans-serif',

    TOOLTIP_BACKGROUND: 'lightyellow',
    TOOLTIP_FONT_SIZE: '12px',
    TOOLTIP_COLOR: 'black',
    TOOLTIP_PADDING: '4px 8px',
    TOOLTIP_BORDER: '1px solid gray',
    TOOLTIP_BORDER_RADIUS: '6px',
    TOOLTIP_XOFFSET: 12,
    TOOLTIP_YOFFSET: 12,
    TOOLTIP_BOX_SHADOW: '0px 0px 3px #AAA',
    TOOLTIP_ZINDEX: 100000,
    TOOLTIP_INITIAL_DELAY: 750,
    TOOLTIP_RESHOW_DELAY: 500,
    TOOLTIP_DISMISS_DELAY: 4000,

    ZOOM_MAX: 5,
    ZOOM_MIN: 0.1,
    ZOOM_INCREMENT: 1.3,
    ZOOM_ANIMATE: true,

    COLUMN_INNER_TEXT: true,
    COLUMN_WIDTH: 80,
    COLUMN_HORIZONTAL_ALIGN: '',
    COLUMN_PROPERTY_TYPE: 'accessor', // 'field', 'accessor', 'style', 'client'
    COLUMN_VALUE_TYPE: 'string', // 'string', 'boolean', 'color', 'int', 'number'
    COLUMN_EDITABLE: false,
    COLUMN_SORTABLE: true,
    COLUMN_VISIBLE: true,
    COLUMN_RESIZABLE: true,
    COLUMN_MOVABLE: true,
    COLUMN_RENDER_CELL: null,
    COLUMN_RENDER_HEADER: null,

    PROPERTY_INNER_TEXT: true,
    PROPERTY_HORIZONTAL_ALIGN: '',
    PROPERTY_PROPERTY_TYPE: 'accessor', // 'field', 'accessor', 'style', 'client'
    PROPERTY_VALUE_TYPE: 'string', // 'string', 'boolean', 'color', 'int', 'number'
    PROPERTY_EDITABLE: false,
    PROPERTY_CATEGORY_NAME: null,
    PROPERTY_RENDER_NAME: null,
    PROPERTY_RENDER_VALUE: null,
    PROPERTY_RENDER_EDITOR: null,

    TAB_WIDTH: 100,
    TAB_CLOSABLE: false,
    TAB_RESIZABLE: true,
    TAB_MOVABLE: true,
    TAB_DISABLED: false,
    TAB_VISIBLE: true,

    ACCORDION_EXPAND_ICON: 'expand_icon',
    ACCORDION_COLLAPSE_ICON: 'collapse_icon',
    ACCORDION_TITLE_HEIGHT: 20,
    ACCORDION_TITLE_BACKGROUND: '#EBEBEB',
    ACCORDION_BORDER_BOTTOM_COLOR: 'lightgray',
    ACCORDION_ICON_POSITION: 'left',

    TITLEPANE_TITLE_HEIGHT: 20,
    TITLEPANE_TITLE_BACKGROUND: '#DDD',
    TITLEPANE_TITLE_HORIZONTAL_ALIGN: 'left',

    BORDERPANE_HGAP: 0,
    BORDERPANE_VGAP: 0,

    CHARTPANE_TITLE_HEIGHT: 20,
    CHARTPANE_TITLE_HORIZONTAL_ALIGN: 'center',
    CHARTPANE_LEGEND_ORIENTATION: 'bottom', // top right bottom left
    CHARTPANE_LEGEND_WIDTH: 80,

    LEGENDPANE_ICON_WIDTH: 10,
    LEGENDPANE_ICON_HEIGHT: 10,
    LEGENDPANE_ICON_RADIUS: 0,
    LEGENDPANE_ROW_HEIGHT: 20,
    LEGENDPANE_ORIENTATION: 'horizontal', // 'horizontal' 'vertical'
    LEGENDPANE_HIDDEN_COLOR: '#BABBBC',
    LEGENDPANE_SELECT_BACKGROUND_COLOR: '#00007D',
    LEGENDPANE_SELECT_FOREGROUND_COLOR: '#FFFFFF',

    CHART_TOOLTIP_ENABLED: true,
    CHART_SELECT_TOLERANCE: 0,
    CHART_XGAP: 6,
    CHART_YGAP: 6,
    CHART_XZOOM_ENABLED: true,
    CHART_YZOOM_ENABLED: true,
    CHART_XTRANSLATE_ENABLED: true,
    CHART_YTRANSLATE_ENABLED: true,
    CHART_DOUBLE_CLICK_TO_RESET: true,
    CHART_VALUE_VISIBLE: true,
    CHART_VALUE_FONT: null,
    CHART_BACKGROUND_VISIBLE: false,
    CHART_BACKGROUND_FILL: true,
    CHART_BACKGROUND_FILL_COLOR: 'rgba(50,50,50,0.11)',
    CHART_BACKGROUND_OUTLINE_WIDTH: 1,
    CHART_BACKGROUND_OUTLINE_COLOR: 'rgba(50,50,50,0.11)',
    CHART_BACKGROUND_GRADIENT: 'linear.north',
    CHART_BACKGROUND_GRADIENT_COLOR: '#FFFFFF',

    PIECHART_TYPE: 'oval', // 'oval' 'circle' 'line' 'donut' 'ovalDonut'
    PIECHART_START_ANGLE: 0,
    PIECHART_SELECT_OFFSET: 5,
    PIECHART_SHADOW_OFFSET: 1,
    PIECHART_SHADOW_COLOR: '#C2CFF1',
    PIECHART_LINE_RATE: 0.5,
    PIECHART_DONUT_RATE: 0.5,
    PIECHART_VALUE_POSITION: 0.5,

    BARCHART_TYPE: 'default', // 'default' 'group' 'stack' 'layer' 'percent' 
    BARCHART_UPPER_LIMIT: null,
    BARCHART_LOWER_LIMIT: 0,
    BARCHART_XAXIS_LINE_COLOR: '#808080',
    BARCHART_XAXIS_LINE_WIDTH: 1,
    BARCHART_XAXIS_TEXT_COLOR: '#000000',
    BARCHART_XAXIS_TEXT_FONT: null,
    BARCHART_YAXIS_LINE_COLOR: '#808080',
    BARCHART_YAXIS_LINE_WIDTH: 1,
    BARCHART_YAXIS_TEXT_COLOR: '#000000',
    BARCHART_YAXIS_TEXT_FONT: null,
    BARCHART_XSCALE_TEXT_FONT: null,
    BARCHART_XSCALE_TEXT_COLOR: '#000000',
    BARCHART_XSCALE_TEXT_ORIENTATION: 'horizontal', // 'horizontal' 'vertical'
    BARCHART_YSCALE_TEXT_VISIBLE: true,
    BARCHART_YSCALE_TEXT_COLOR: '#000000',
    BARCHART_YSCALE_TEXT_FONT: null,
    BARCHART_YSCALE_LINE_COLOR: '#808080',
    BARCHART_YSCALE_LINE_WIDTH: 0.3,
    BARCHART_YSCALE_VALUE_GAP: 0,
    BARCHART_YSCALE_PIXEL_GAP: 20,
    BARCHART_YSCALE_MIN_TEXT_VISIBLE: false,

    LINECHART_INTERRUPTABLE: true,
    LINECHART_UPPER_LIMIT: null,
    LINECHART_LOWER_LIMIT: null,
    LINECHART_XAXIS_LINE_COLOR: '#808080',
    LINECHART_XAXIS_LINE_WIDTH: 1,
    LINECHART_XAXIS_TEXT_COLOR: '#000000',
    LINECHART_XAXIS_TEXT_FONT: null,
    LINECHART_YAXIS_LINE_COLOR: '#808080',
    LINECHART_YAXIS_LINE_WIDTH: 1,
    LINECHART_YAXIS_TEXT_COLOR: '#000000',
    LINECHART_YAXIS_TEXT_FONT: null,
    LINECHART_XSCALE_TEXT_FONT: null,
    LINECHART_XSCALE_TEXT_COLOR: '#000000',
    LINECHART_XSCALE_TEXT_ORIENTATION: 'horizontal', // 'horizontal' 'vertical'
    LINECHART_XSCALE_LINE_COLOR: '#808080',
    LINECHART_XSCALE_LINE_WIDTH: 0.3,
    LINECHART_YSCALE_TEXT_VISIBLE: true,
    LINECHART_YSCALE_TEXT_COLOR: '#000000',
    LINECHART_YSCALE_TEXT_FONT: null,
    LINECHART_YSCALE_LINE_COLOR: '#808080',
    LINECHART_YSCALE_LINE_WIDTH: 0.3,
    LINECHART_YSCALE_VALUE_GAP: 0,
    LINECHART_YSCALE_PIXEL_GAP: 20,
    LINECHART_YSCALE_MIN_TEXT_VISIBLE: false,
    LINECHART_VALUESPANCOUNT:1,

    BUBBLECHART_UPPER_LIMIT: null,
    BUBBLECHART_LOWER_LIMIT: null,
    BUBBLECHART_XAXIS_UPPER_LIMIT: null,
    BUBBLECHART_XAXIS_LOWER_LIMIT: null,
    BUBBLECHART_XAXIS_LINE_COLOR: '#808080',
    BUBBLECHART_XAXIS_LINE_WIDTH: 1,
    BUBBLECHART_XAXIS_TEXT_COLOR: '#000000',
    BUBBLECHART_XAXIS_TEXT_FONT: null,
    BUBBLECHART_YAXIS_LINE_COLOR: '#808080',
    BUBBLECHART_YAXIS_LINE_WIDTH: 1,
    BUBBLECHART_YAXIS_TEXT_COLOR: '#000000',
    BUBBLECHART_YAXIS_TEXT_FONT: null,
    BUBBLECHART_XSCALE_TEXT_FONT: null,
    BUBBLECHART_XSCALE_TEXT_COLOR: '#000000',
    BUBBLECHART_XSCALE_TEXT_ORIENTATION: 'horizontal', // 'horizontal' 'vertical'
    BUBBLECHART_XSCALE_LINE_COLOR: '#808080',
    BUBBLECHART_XSCALE_LINE_WIDTH: 0.3,
    BUBBLECHART_YSCALE_TEXT_VISIBLE: true,
    BUBBLECHART_YSCALE_TEXT_COLOR: '#000000',
    BUBBLECHART_YSCALE_TEXT_FONT: null,
    BUBBLECHART_YSCALE_LINE_COLOR: '#808080',
    BUBBLECHART_YSCALE_LINE_WIDTH: 0.3,
    BUBBLECHART_YSCALE_VALUE_GAP: 0,
    BUBBLECHART_YSCALE_PIXEL_GAP: 20,
    BUBBLECHART_YSCALE_MIN_TEXT_VISIBLE: false,
    BUBBLECHART_SELECT_SHADOW_COLOR: '#000000',
    BUBBLECHART_SELECT_SHADOW_OFFSET: 3,

    RADARCHART_AXIS_TEXT_FONT: null,
    RADARCHART_AXIS_TEXT_COLOR: '#000000',
    RADARCHART_AXIS_TEXT_VISIBLE: true,
    RADARCHART_SCALE_TEXT_FONT: null,
    RADARCHART_SCALE_TEXT_COLOR: '#000000',
    RADARCHART_SCALE_TEXT_VISIBLE: true,
    RADARCHART_AXIS_VISIBLE: true,
    RADARCHART_AXIS_LINE_COLOR: '#808080',
    RADARCHART_AXIS_LINE_WIDTH: 3,
    RADARCHART_AXIS_START_ANGLE: 0,
    RADARCHART_RING_VISIBLE: true,
    RADARCHART_RING_TYPE: 'line', // 'line', 'arc'
    RADARCHART_RING_LINE_COLOR: '#808080',
    RADARCHART_RING_LINE_WIDTH: 1,
    RADARCHART_SCALE_COUNT: 5,
    RADARCHART_SCALE_MAXVALUE: 1,
    RADARCHART_SCALE_MINVALUE: 0,
    RADARCHART_ANCHOR_VISIBLE: true,
    RADARCHART_AREA_FILL: true,
    RADARCHART_AREA_FILL_ALPHA: 0.2,
    RADARCHART_AREA_SELECT_FILL_ALPHA: 0.5,

    DIALCHART_UPPER_LIMIT: 100,
    DIALCHART_LOWER_LIMIT: 0,
    DIALCHART_START_ANGLE: 0,
    DIALCHART_END_ANGLE: 360,
    DIALCHART_INNER_RADIUS: 0.8,
    DIALCHART_COLOR_RANGE_FILL_COLOR: '#808080',
    DIALCHART_OUTLINE_WIDTH: 0,
    DIALCHART_OUTLINE_COLOR: '#808080',

    DIALCHART_SCALE_INSIDE: true,
    DIALCHART_MAJOR_SCALE_COUNT: 11,
    DIALCHART_MAJOR_SCALE_LINE_WIDTH: 2,
    DIALCHART_MAJOR_SCALE_LINE_LENGTH: 8,
    DIALCHART_MAJOR_SCALE_LINE_COLOR: '#000000',
    DIALCHART_MINOR_SCALE_COUNT: 4,
    DIALCHART_MINOR_SCALE_LINE_WIDTH: 1,
    DIALCHART_MINOR_SCALE_LINE_LENGTH: 4,
    DIALCHART_MINOR_SCALE_LINE_COLOR: '#000000',
    DIALCHART_SCALE_TEXT_VISIBLE: true,
    DIALCHART_SCALE_UPPER_LIMIT_TEXT_VISIBLE: true,
    DIALCHART_SCALE_LOWER_LIMIT_TEXT_VISIBLE: true,
    DIALCHART_SCALE_TEXT_FONT: null,
    DIALCHART_SCALE_TEXT_COLOR: '#000000',
    DIALCHART_PIVOT_RADIUS: 10,
    DIALCHART_PIVOT_FILL: true,
    DIALCHART_PIVOT_FILL_COLOR: '#808080',
    DIALCHART_PIVOT_OUTLINE_WIDTH: 0,
    DIALCHART_PIVOT_OUTLINE_COLOR: '#808080',
    DIALCHART_VALUE_POSITION: 0.5,
    DIALCHART_INNER_DARKER_RADIUS: 10,
    DIALCHART_OUTER_BRIGHTER_RADIUS: 10,
    DIALCHART_SELECT_SHADOW_COLOR: '#000000',
    DIALCHART_SELECT_SHADOW_OFFSET: 3,

    TABPANE_TAB_GAP: 1,
    TABPANE_TAB_RADIUS: 0,
    TABPANE_TAB_HEIGHT: 24,
    TABPANE_TAB_ORIENTATION: 'top',
    TABPANE_RESIZE_TOLERANCE: 3,
    TABPANE_TAB_BACKGROUND: '#EBEBEB',
    TABPANE_DISABLED_COLOR: '#BABBBC',
    TABPANE_SELECT_BACKGROUND: 'white',
    TABPANE_MOVE_BACKGROUND: 'rgba(184,211,240,0.7)',
    TABPANE_INSERT_BACKGROUND: 'orange',
    TABPANE_HORIZONTAL_ALIGN: 'center',
    TABPANE_CLOSE_ICON: 'close_icon',
    TABPANE_SELECT_NEXT_ON_CLOSE: true,
    TABPANE_SELECT_NEXT_ON_INVISIBLE: true,

    LISTBASE_INNER_TEXT: true,
    LIST_ROW_HEIGHT: 19,
    LIST_INDENT: 2,
    LIST_ROW_LINE_WIDTH: 0,
    LIST_ROW_LINE_COLOR: '#DDD',
    LIST_MAKE_VISIBLE_ON_SELECTED: true,
    LIST_KEYBOARD_REMOVE_ENABLED: true,
    LIST_KEYBOARD_SELECT_ENABLED: true,

    TREE_ROW_HEIGHT: 19,
    TREE_INDENT: 16,
    TREE_ROW_LINE_WIDTH: 0,
    TREE_ROW_LINE_COLOR: '#DDD',
    TREE_MAKE_VISIBLE_ON_SELECTED: true,
    TREE_KEYBOARD_REMOVE_ENABLED: true,
    TREE_KEYBOARD_SELECT_ENABLED: true,
    TREE_EXPAND_ICON: 'expand_icon',
    TREE_COLLAPSE_ICON: 'collapse_icon',
    TREE_LINE_TYPE:'none',//'dotted','solid'
    TREE_LINE_THICKNESS:2,
    TREE_LINE_COLOR:'#000000',
    TREE_LINE_ALPHA:1,
    TREE_LINE_DASH:[4,2],
    TREE_TOOLTIP_ENABLED:true,

    TABLE_ROW_HEIGHT: 19,
    TABLE_ROW_LINE_WIDTH: 1,
    TABLE_ROW_LINE_COLOR: '#DDD',
    TABLE_COLUMN_LINE_WIDTH: 1,
    TABLE_COLUMN_LINE_COLOR: '#DDD',
    TABLE_MAKE_VISIBLE_ON_SELECTED: true,
    TABLE_KEYBOARD_REMOVE_ENABLED: true,
    TABLE_KEYBOARD_SELECT_ENABLED: true,
    TABLE_EDITABLE: false,

    TABLEHEADER_HEIGHT: 24,
    TABLEHEADER_RESIZE_TOLERANCE: 3,
    TABLEHEADER_BACKGROUND: '#EBEBEB',
    TABLEHEADER_MOVE_BACKGROUND: 'rgba(184,211,240,0.7)',
    TABLEHEADER_INSERT_BACKGROUND: 'orange',
    TABLEHEADER_COLUMN_LINE_COLOR: '#DDD',
    TABLEHEADER_SORT_DESC_ICON: 'sort_desc',
    TABLEHEADER_SORT_ASC_ICON: 'sort_asc',
    TABLEHEADER_SORT_ICON_POSITION: '98% 50%',

    TREETABLE_ROW_HEIGHT: 19,
    TREETABLE_INDENT: 16,
    TREETABLE_ROW_LINE_WIDTH: 1,
    TREETABLE_ROW_LINE_COLOR: '#DDD',
    TREETABLE_COLUMN_LINE_WIDTH: 1,
    TREETABLE_COLUMN_LINE_COLOR: '#DDD',
    TREETABLE_MAKE_VISIBLE_ON_SELECTED: true,
    TREETABLE_KEYBOARD_REMOVE_ENABLED: true,
    TREETABLE_KEYBOARD_SELECT_ENABLED: true,
    TREETABLE_EXPAND_ICON: 'expand_icon',
    TREETABLE_COLLAPSE_ICON: 'collapse_icon',
    TREETABLE_EDITABLE: false,

    PROPERTYSHEET_AUTO_ADJUSTABLE: true,
    PROPERTYSHEET_INDENT: 16,
    PROPERTYSHEET_ROW_HEIGHT: 19,
    PROPERTYSHEET_ROW_LINE_WIDTH: 1,
    PROPERTYSHEET_COLUMN_LINE_WIDTH: 1,
    PROPERTYSHEET_BORDER_COLOR: '#EBEBEB',
    PROPERTYSHEET_EXPAND_ICON: 'expand_icon',
    PROPERTYSHEET_COLLAPSE_ICON: 'collapse_icon',
    PROPERTYSHEET_PROPERTY_NAME_WIDTH: 100,
    PROPERTYSHEET_PROPERTY_NAME_HORIZONTAL_ALIGN: '',
    PROPERTYSHEET_SUM_WIDTH: 200,
    PROPERTYSHEET_RESIZE_TOLERANCE: 3,
    PROPERTYSHEET_EDITABLE: false,
    PROPERTYSHEET_CATEGORIZABLE: true,
    PROPERTYSHEET_EXPAND_CATEGORY: true,
    
    POPUPMENU_SUBNENU_ENABLE_ICON: 'submenu_enable_icon',
    POPUPMENU_SUBNENU_DISABLE_ICON: 'submenu_disable_icon',
    POPUPMENU_CHECKBOX_SELECTED_ICON: 'checkbox_selected_icon',
    POPUPMENU_CHECKBOX_UNSELECTED_ICON: 'checkbox_unselected_icon',
    POPUPMENU_RADIOBUTTON_SELECTED_ICON: 'radiobutton_selected_icon',
    POPUPMENU_RADIOBUTTON_UNSELECTED_ICON: 'radiobutton_unselected_icon',

    SPLITPANE_ORIENTATION: 'horizontal',
    SPLITPANE_POSITION: 0.5,
    SPLITPANE_DIVIDER_WIDTH: 6,
    SPLITPANE_DIVIDER_BACKGROUND: '#CCCCFF',
    SPLITPANE_DIVIDER_OPACITY: 0.5,
    SPLITPANE_MASK_BACKGROUND: '',

    NODE_WIDTH: 50,
    NODE_HEIGHT: 50,
    IMAGE_NODE: 'node_image',
    IMAGE_GROUP: 'group_image',
    IMAGE_SUBNETWORK: 'subnetwork_image',
    ICON_DATABOX: 'databox_icon',
    ICON_DATA: 'data_icon',
    ICON_NODE: 'node_icon',
    ICON_LINK: 'link_icon',
    ICON_GROUP: 'group_icon',
    ICON_SUBNETWORK: 'subnetwork_icon',
    ICON_GRID: 'grid_icon',
    ICON_BUS: 'bus_icon',
    ICON_SHAPENODE: 'shapenode_icon',
    ICON_SHAPELINK: 'shapelink_icon',
    ICON_LINKSUBNETWORK: 'linksubnetwork_icon',
    ICON_SHAPESUBNETWORK: 'shapesubnetwork_icon',
    LAYER_DEFAULT_ID: 'default',
    LAYER_DEFAULT_NAME: 'default',

    ATTACHMENT_POINTER_LENGTH: 10,
    ATTACHMENT_POINTER_WIDTH: 8,
    ATTACHMENT_CORNER_RADIUS: 5,
    ATTACHMENT_CONTENT_WIDTH: 30,
    ATTACHMENT_CONTENT_HEIGHT: 20,
    ATTACHMENT_POSITION: 'topright.topright',
    ATTACHMENT_XOFFSET: 0,
    ATTACHMENT_YOFFSET: 0,
    ATTACHMENT_PADDING: 0,
    ATTACHMENT_PADDING_LEFT: 0,
    ATTACHMENT_PADDING_RIGHT: 0,
    ATTACHMENT_PADDING_TOP: 0,
    ATTACHMENT_PADDING_BOTTOM: 0,
    ATTACHMENT_DIRECTION: 'right',
    ATTACHMENT_FILL: false,
    ATTACHMENT_FILL_COLOR: '#000000',
    ATTACHMENT_GRADIENT: null,
    ATTACHMENT_GRADIENT_COLOR: '#FFFFFF',
    ATTACHMENT_OUTLINE_WIDTH: -1,
    ATTACHMENT_OUTLINE_COLOR: '#000000',
    ATTACHMENT_CAP: 'butt',
    ATTACHMENT_JOIN: 'miter',
    ATTACHMENT_SHADOWABLE: true,

    NETWORK_TOOLTIP_ENABLED: true,
    NETWORK_SELECT_MODE: 'mix',
    NETWORK_MAKE_VISIBLE_ON_SELECTED: true,
    NETWORK_NO_AGENT_LINK_VISIBLE: false,
    NETWORK_REMOVE_ELEMENTUI_ON_INVISIBLE: false,
    NETWORK_SUBNETWORK_ANIMATE: true,
    NETWORK_SENDTOTOP_ON_SELECTED: true,
    NETWORK_KEYBOARD_REMOVE_ENABLED: true,
    NETWORK_KEYBOARD_SELECT_ENABLED: true,
    NETWORK_RECT_SELECT_ENABLED: true,
    NETWORK_DOUBLECLICK_TO_SUBNETWORK: true,
    NETWORK_DOUBLECLICK_TO_UPSUBNETWORK: true,
    NETWORK_DOUBLECLICK_TO_EMPTYSUBNETWORK: true,
    NETWORK_DOUBLECLICK_TO_LINKBUNDLE: true,
    NETWORK_DOUBLECLICK_TO_GROUPEXPAND: true,
    NETWORK_SELECT_OUTLINE_COLOR: '#2877A8',
    NETWORK_SELECT_OUTLINE_WIDTH: 1,
    NETWORK_SELECT_FILL_COLOR: 'rgba(184,211,240,0.4)',
    NETWORK_LAZYMOVE_OUTLINE_COLOR: '#2877A8',
    NETWORK_LAZYMOVE_OUTLINE_WIDTH: 1,
    NETWORK_LAZYMOVE_FILL_COLOR: 'rgba(184,211,240,0.4)',
    NETWORK_LAZYMOVE_FILL: true,
    NETWORK_LAZYMOVE_ANIMATE: true,
    NETWORK_RESIZE_POINT_SIZE: 3,
    NETWORK_RESIZE_POINT_FILL_COLOR: '#FFFFFF',
    NETWORK_RESIZE_POINT_OUTLINE_COLOR: '#000000',
    NETWORK_RESIZE_POINT_OUTLINE_WIDTH: 1,
    NETWORK_RESIZE_LINE_COLOR: '#000000',
    NETWORK_RESIZE_LINE_WIDTH: 1,
    NETWORK_RESIZE_ANIMATE: true,
    NETWORK_EDIT_POINT_SIZE: 3,
    NETWORK_EDIT_POINT_FILL_COLOR: '#FFFF00',
    NETWORK_EDIT_POINT_OUTLINE_COLOR: '#000000',
    NETWORK_EDIT_POINT_OUTLINE_WIDTH: 1,
    NETWORK_EDIT_LINE_COLOR: 'rgba(184,211,240,0.7)',
    NETWORK_EDIT_LINE_WIDTH: 2,
    NETWORK_ROTATE_POINT_SIZE: 5,
    NETWORK_ROTATE_POINT_FILL_COLOR: '#FFFF00',
    NETWORK_ROTATE_POINT_OFFSET: 15,
    NETWORK_ROTATE_POINT_OUTLINE_WIDTH: 1,
    NETWORK_ROTATE_POINT_OUTLINE_COLOR: 'rgba(0,0,0,1)',
    NETWORK_ROTATE_SCALE_FILL_COLOR: 'rgb(227,166,103)',
    NETWORK_ROTATE_SCALE_FONT_COLOR: '#FFFFFF',
    NETWORK_ROTATE_SCALE_WIDTH: 30,
    NETWORK_ROTATE_SCALE_HEIGHT: 20,
    NETWORK_LIMIT_ELEMENT_INPOSITIVE_LOCATION: true,
    NETWORK_LINK_FLOW_STEPPING: 3,
    NETWORK_LINK_FLOW_COLOR: "#FF0000",
    NETWORK_LINK_FLOW_INTERVAL: 600,
    NETWORK_SELECTION_TOLERANCE: 2,
    NETWORK_TRANSPARENT_SELECTION_ENABLE:false,

    SHOW_ALARM_IN_ATTACHMENT_DIV: true,
    SHOW_LABEL_IN_ATTACHMENT_DIV: false,
    SHOW_LABEL2_IN_ATTACHMENT_DIV: false,
    SHOW_ICON_IN_ATTACHMENT_DIV: false,
    SHOW_EDIT_IN_ATTACHMENT_DIV: false,

    OVERVIEW_FILL_COLOR: 'rgba(184,211,240,0.4)',
    OVERVIEW_OUTLINE_COLOR: '#B8D3F0',
    OVERVIEW_OUTLINE_WIDTH: 1,
    OVERVIEW_SELECT_COLOR: '#0000FF',
    OVERVIEW_SELECT_WIDTH: 1,
    OVERVIEW_PADDING: 1,
    OVERVIEW_ANIMATE: true,
    OVERVIEW_MAX_PACKING_WIDTH: -1,
    OVERVIEW_MAX_PACKING_HEIGHT: -1,

    TOUCH_MOVE_THRESHOLD:5,
    TOUCH_RECT_SELECT_THRESHOLD:20,
    TOUCH_ZOOM_THRESHOLD:30,

    LINK_BUNDLE_AGENT_FUNCTION: null,
    IS_LINK_ADJUSTED_TO_BOTTOM: false,

    ELEMENTUI_FUNCTION: function (network, element) {
        var clazz = element.getElementUIClass();
        if (clazz) {
            return new clazz(network, element);
        }
        return null;
    },

    CANVASUI_FUNCTION: function (network, element) {
        var clazz = element.getCanvasUIClass();
        if (clazz) {
            return new clazz(network, element);
        }
        return null;
    },
    VECTORUI_FUNCTION : function(network,element){
    	var clazz = element.getVectorUIClass();
    	if(clazz){
    		return new clazz(network,element);
    	}
    	return null;
    },
    KEEP_DEFAULT_FUNCTION: function (e) {
        if (e.target.keepDefault || e.target.getAttribute("keepDefault")) {
            return true;
        }
        if (e.target.parentNode && (e.target.parentNode.keepDefault || e.target.parentNode.getAttribute("keepDefault"))) {
            return true;
        }
        if (e.shiftKey) {
            return true;
        }
        return false;
    },
    SORT_FUNCTION: function (v1, v2) {
        if (v1 === v2) {
            return 0;
        }
        if (v1 == null && v2 != null) {
            return 1;
        }
        if (v1 != null && v2 == null) {
            return -1;
        }
        if (v1 == null && v2 == null) {
            return 0;
        }
        var t1 = typeof v1;
        var t2 = typeof v2;
        var value;
        if (t1 === 'string' && t2 === 'string') {
            value = v1.localeCompare(v2);
        }
        if (t1 === 'number' && t2 === 'number') {
            value = v1 - v2;
        }
        if (value === undefined) {
            value = ('' + v1).localeCompare('' + v2);
        }
        if (value > 0) {
            return 1;
        }
        else if (value < 0) {
            return -1;
        }
        return 0;
    },
    CENTER_LOCATION: false,
    PIXEL_FILTER_FUNCTION: function(sourceColor, filterColor) {
        if (!filterColor) {
            return sourceColor;
        }
        var brightness = sourceColor.r * 0.30 + sourceColor.g * 0.59 + sourceColor.b * 0.11;
        return {
            r: Math.floor(filterColor.r * brightness / 255),
            g:Math.floor(filterColor.g * brightness / 255),
            b:Math.floor(filterColor.b * brightness / 255),
        }
    }
};

(function () {
    var D = $Defaults;

    // override twaver defaults
    if (window.OverrideTWaverDefaults) {
        for (var name in OverrideTWaverDefaults) {
            D[name] = OverrideTWaverDefaults[name];
        }
    }

    // italic bold 12px Geneva,Helvetica,Arial,sans-serif
    if (D.VIEW_FONT_SIZE && D.VIEW_FONT_FAMILY) {
        D.FONT = D.VIEW_FONT_SIZE + ' ' + D.VIEW_FONT_FAMILY;
    } else {
        D.FONT = document.createElement('canvas').getContext('2d').font;
    }

    if (!D.CHART_VALUE_FONT) D.CHART_VALUE_FONT = '10px ' + D.VIEW_FONT_FAMILY;

    if (!D.BARCHART_XSCALE_TEXT_FONT) D.BARCHART_XSCALE_TEXT_FONT = '10px ' + D.VIEW_FONT_FAMILY;
    if (!D.BARCHART_YSCALE_TEXT_FONT) D.BARCHART_YSCALE_TEXT_FONT = '10px ' + D.VIEW_FONT_FAMILY;
    if (!D.BARCHART_XAXIS_TEXT_FONT) D.BARCHART_XAXIS_TEXT_FONT = '12px ' + D.VIEW_FONT_FAMILY;
    if (!D.BARCHART_YAXIS_TEXT_FONT) D.BARCHART_YAXIS_TEXT_FONT = '12px ' + D.VIEW_FONT_FAMILY;

    if (!D.LINECHART_XSCALE_TEXT_FONT) D.LINECHART_XSCALE_TEXT_FONT = '10px ' + D.VIEW_FONT_FAMILY;
    if (!D.LINECHART_YSCALE_TEXT_FONT) D.LINECHART_YSCALE_TEXT_FONT = '10px ' + D.VIEW_FONT_FAMILY;
    if (!D.LINECHART_XAXIS_TEXT_FONT) D.LINECHART_XAXIS_TEXT_FONT = '12px ' + D.VIEW_FONT_FAMILY;
    if (!D.LINECHART_YAXIS_TEXT_FONT) D.LINECHART_YAXIS_TEXT_FONT = '12px ' + D.VIEW_FONT_FAMILY;

    if (!D.BUBBLECHART_XAXIS_TEXT_FONT) D.BUBBLECHART_XAXIS_TEXT_FONT = '12px ' + D.VIEW_FONT_FAMILY;
    if (!D.BUBBLECHART_YAXIS_TEXT_FONT) D.BUBBLECHART_YAXIS_TEXT_FONT = '12px ' + D.VIEW_FONT_FAMILY;
    if (!D.BUBBLECHART_XSCALE_TEXT_FONT) D.BUBBLECHART_XSCALE_TEXT_FONT = '10px ' + D.VIEW_FONT_FAMILY;
    if (!D.BUBBLECHART_YSCALE_TEXT_FONT) D.BUBBLECHART_YSCALE_TEXT_FONT = '10px ' + D.VIEW_FONT_FAMILY;

    if (!D.RADARCHART_AXIS_TEXT_FONT) D.RADARCHART_AXIS_TEXT_FONT = '12px ' + D.VIEW_FONT_FAMILY;
    if (!D.RADARCHART_SCALE_TEXT_FONT) D.RADARCHART_SCALE_TEXT_FONT = '10px ' + D.VIEW_FONT_FAMILY;

    if (!D.DIALCHART_SCALE_TEXT_FONT) D.DIALCHART_SCALE_TEXT_FONT = '10px ' + D.VIEW_FONT_FAMILY;
})();
twaver.Defaults = $Defaults;
_twaver.ext('twaver.Defaults', Object, {});
